### ISSUE TITLE
Database Set-up

### ISSUE THREAD

**Issue by chriskwong91** [SweatyFigs/SweatyFigs#74]

**Comment by brianzhou13** [comment]
a field that we may want to consider is user likes/votes per recipe.
     -this may allow us to further filter or prioritize the results per ingredients sent in.

**Comment by RSiferd2** [comment]
Are we going to use mongo or mysql?

**Comment by chriskwong91** [comment]
@RSiferd2 I have mongo set up right now just to test the authenication process, but we can discuss if we need a sql database or not. Not exactly sure what relational data we have
