### ISSUE TITLE
Mock Up of Landing Page

### ISSUE THREAD

**Issue by chriskwong91** [SweatyFigs/SweatyFigs#8]

**Comment by brianzhou13** [comment]
![img_0097](https://cloud.githubusercontent.com/assets/5092263/18151039/8ddb7a38-6fa0-11e6-8596-b36b73c18a6e.jpg)

added mockups for v1 
-landing page
-search page
-recipe page

**Comment by brianzhou13** [comment]
Going to move this to be complete. :)

**Comment by brianzhou13** [comment]
Resolve #8
